app/finances/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required
from finances.views import (MovementCreateView, MovementUpdateView, MovementDeleteView,
                            MovementMontArchiveView,MovementLastMonth ,MovementAdminListView,
                            WorkersTimeListView, AttendanceReport, AttendanceReportFormClass,
                            AttendaceFullReportClass, UserAccountingTemplateView,
                            ProjectAttendanceReport, OrderCreateView, OrderListView,
                            OrderDetailView, OrderUpdateView, order_complete)

app_name = 'finances'

urlpatterns = [
    path('', MovementCreateView.as_view(), name = 'finances_home'),
    path('currentmonth',MovementLastMonth.as_view(), name='finances_lastmonth'),
    path('movementlist/<int:year>/<int:month>', MovementMontArchiveView.as_view(), name='finances_month'),
    path('movementresume', UserAccountingTemplateView.as_view(), name='finances_resume'),
    path('edit/<int:pk>', MovementUpdateView.as_view(), name = 'finances_edit'),
    path('delete/<int:pk>', MovementDeleteView.as_view(), name='finances_delete'),
    path('workerstime', WorkersTimeListView.as_view(), name='workerstime_list'),
    #path('attendance', AttendanceReport.as_view(), name='attendance_report'),
    path(
        'attendance/<str:inicio>/<str:final>/<str:extra>/<str:adicional>/<str:cliente>',
        AttendaceFullReportClass.as_view(),
        name='attendance_report'),
    path(
        # Formulario para generar reporte de asistencia
        'attendanceform',
        AttendanceReportFormClass.as_view(),
        name='attendance_form',
    ),
    path(
        'projectattendance/<int:pk>',
        ProjectAttendanceReport.as_view(),
        name='projectattendance_report'
    ),
    # path(
    #     'projectattendance/<int:pk>',
    #     permission_required('finances.change_movement')(ProjectAttendanceReport.as_view()),
    #     name = 'projectattendance_report'
    # ),
    path(
        'ordercreate',
        OrderCreateView.as_view(),
        name='order_create',
    ),
    path(
        'orderlist',
        OrderListView.as_view(),
        name = 'order_list',
    ),
    path(
        'orderdetail/<int:pk>',
        OrderDetailView.as_view(),
        name = 'order_detail',
    ),
    path(
        'orderupdate/<int:pk>',
        OrderUpdateView.as_view(),
        name = 'order_update',
    ),
    path(
        'ordercomplete/<int:pk>',
        order_complete,
        name = 'order_complete',
    )
]

app/inxcontrol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('inxcontrol/admin/', admin.site.urls),
    path('inxcontrol/profiles/', include('profiles.urls'), name='profiles'),
    path('inxcontrol/finances/', include('finances.urls'), name='finances'),
    path('inxcontrol/projects/', include('projects.urls'), name='projects'),
    path('inxcontrol/sales/', include('sales.urls'), name='sales'),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

app/profiles/urls.py
from django.urls import path, include
from .views import (UserCreateView, UserListView, UserDetailView, UserUpdateView,
                    SupplierListView, SupplierDetailView,SupplierCreateView, SupplierUpdateView,
                    ClientListView, ClientDetailView,ClientCreateView, ClientUpdateView, 
                    ClientContactUpdateView, ClientContactCreateView,  ClientContactDetailView, ClientContactListView,
                    SupplierContactUpdateView, SupplierContactCreateView,  SupplierContactDetailView, SupplierContactListView,
                    WorkerCreateView, WorkerTimeCreateView, WorkerTimeUpdateView, WorkerTimeWeekArchiveView,
                    WorkerTimeLastWeek, WorkerCostCreateView, WorkerCostUpdateView, WorkerAttendanceWeekView,
                    ClientCombineView, SupplierCategoryCreateView)

from django.contrib.auth.views import LoginView

app_name = 'profiles'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('usercreate', UserCreateView.as_view(), name='user_create'),
    path('userlist', UserListView.as_view(), name='user_list'),
    path('login', LoginView.as_view(), name='user_login'),
    path('detail/<int:pk>', UserDetailView.as_view(), name = 'user_detail'),
    path('userupdate/<int:pk>', UserUpdateView.as_view(), name='user_update'),
    path('workercreate', WorkerCreateView.as_view(), name = 'worker_create'),
    path('workertimecreate', WorkerTimeCreateView.as_view(), name='workertime_create'),
    path('workertimeupdate/<int:pk>', WorkerTimeUpdateView.as_view(), name='workertime_update'),
    path(
        'workertime/<int:year>/week/<int:week>',
        WorkerTimeWeekArchiveView.as_view(),
        name='workertime_week'
    ),
    path(
        # Reporte de asistencia de trabajadores con indicacion de reportes faltantes
        'workersattendance/<str:inicio>/<str:final>/<str:extra>/<str:adicional>/<str:cliente>',
        WorkerAttendanceWeekView.as_view(),
        name='workerattendance_week',
    ),
    path('workertime/last', WorkerTimeLastWeek.as_view(), name='workertime_lastweek'),
    path('workercostcreate/<int:pk>', WorkerCostCreateView.as_view(), name='workercost_create'),
    path('workercostupdate/<int:pk>', WorkerCostUpdateView.as_view(), name='workercost_update'),
    path('clientcreate', ClientCreateView.as_view(), name='client_create'),
    path('clientlist', ClientListView.as_view(), name = 'client_list'),
    path('clientdetail/<int:pk>', ClientDetailView.as_view(), name='client_detail'),
    path('clientupdate/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('suppliercreate', SupplierCreateView.as_view(), name='supplier_create'),
    path('supplierlist', SupplierListView.as_view(), name='supplier_list'),
    path('supplierdetail/<int:pk>', SupplierDetailView.as_view(), name='supplier_detail'),
    path('supplierupdate/<int:pk>', SupplierUpdateView.as_view(), name='supplier_update'),
    path('clientcontactcreate', ClientContactCreateView.as_view(), name='clientcontact_create'),
    path('clientcontactlist', ClientContactListView.as_view(), name = 'clientcontact_list'),
    path('clientcontactdetail/<int:pk>', ClientContactDetailView.as_view(), name='clientcontact_detail'),
    path('clientcontactupdate/<int:pk>', ClientContactUpdateView.as_view(), name='clientcontact_update'),
    path('clientcombination', ClientCombineView.as_view(), name='client_combination'),
    path('suppliercontactcreate', SupplierContactCreateView.as_view(), name='suppliercontact_create'),
    path('suppliercontactlist', SupplierContactListView.as_view(), name = 'suppliercontact_list'),
    path('suppliercontactdetail/<int:pk>', SupplierContactDetailView.as_view(), name='suppliercontact_detail'),
    path('suppliercontactupdate/<int:pk>', SupplierContactUpdateView.as_view(), name='suppliercontact_update'),
    path('suppliercategorycreate', SupplierCategoryCreateView.as_view(), name='suppliercategory_create'),
]

app/projects/urls.py
from django.urls import path

from .views import ( ProjectCreateView, ProjectListView, ProjectDetailView,
                     ProjectUpdateView, ActivityCreateView, ActivityDetailView,
                     ActivityListView, RequirementCreateView, RequirementListView,
                     ReportCreateView, ReportListView, ReportUpdateView, ActivityUpdateView,
                     ReportDetailView, PhotoCreateView, RequirementUpdateView,
                     ActivityDeleteView, ActivityCompactListView, ReportCardListView,
                     ActivityProgressCreateView, ReportProgressCreateView,
                     ActivityProgressUpdateView, ReportProgressUpdateView,
                     ReportProgressDeleteView, ActivityProgressDeleteView, SearchListView,
                     ReportDeleteView, ReportDayArchiveView, ReportLastdayArchiveView,
                     ActivityPrintView, RequirementCompleteView, ProjectCostUpdateView,
                     ProjectDeleteView, ReportMaterialsCreateView, ReportMaterialsDeleteView,
                     ReportListPrint, ActivityReportView, UserTimeReportUpdateView,
                     UserTimeReportConvertView, UserTimeReportAddView, ActivityWorkingListView,
                     UserReportListView )
app_name = 'projects'

urlpatterns = [
    path('projectlist', ProjectListView.as_view(), name='project_list' ),
    path('projectcreate', ProjectCreateView.as_view(),name='project_create'),
    path('projectdelete/<int:pk>', ProjectDeleteView.as_view(),name='project_delete'),
    path("projectdetail/<int:pk>", ProjectDetailView.as_view(), name = 'project_detail'),
    path('projectupdate/<int:pk>', ProjectUpdateView.as_view(), name='project_update' ),
    path('projectcostupdate/<int:pk>', ProjectCostUpdateView.as_view(), name='projectcost_update' ),
    path('activitylist', ActivityListView.as_view(), name='activity_list'),
    path('activityprint', ActivityPrintView.as_view(), name='activity_print'),
    path('activitycompactlist', ActivityCompactListView.as_view(), name='activity_compactlist'),
    path('activitycreate', ActivityCreateView.as_view(), name='activity_create'),
    path('activitydetail/<int:pk>', ActivityDetailView.as_view(), name='activity_detail'),
    path('activityupdate/<int:pk>', ActivityUpdateView.as_view(), name='activity_update'),
    path('activitydelete/<int:pk>', ActivityDeleteView.as_view(), name='activity_delete'),
    path('activityworkinglist', ActivityWorkingListView.as_view(), name='activity_workinglist'),
    path('activityreport', ActivityReportView.as_view(), name='activity_report'),
    path('activityprogresscreate/<int:pk>', ActivityProgressCreateView.as_view(), name='activityprogress_create'),
    path('activityprogressupdate/<int:pk>', ActivityProgressUpdateView.as_view(), name='activityprogress_update'),
    path('activityprogressdelete/<int:pk>', ActivityProgressDeleteView.as_view(), name='activityprogress_delete'),
    path('requirementcreate', RequirementCreateView.as_view(), name='requirement_create'),
    path('requirementupdate/<int:pk>', RequirementUpdateView.as_view(), name='requirement_update'),
    path('requirementlist', RequirementListView.as_view(), name='requirement_list'),
    path('requirementcomplete/<int:pk>', RequirementCompleteView.as_view(), name='requirement_complete'),
    path('reportlist', ReportListView.as_view(), name='report_list'),
    path('reports/lastday', ReportLastdayArchiveView.as_view(), name='report_lastday'),
    path('reports/<int:year>/<str:month>/<int:day>/', ReportDayArchiveView.as_view(), name='report_dayarchive'),
    path('reportcardlist', ReportCardListView.as_view(), name='report_cardlist'),
    path('reportcreate', ReportCreateView.as_view(), name='report_create'),
    path('reportcreate/<int:pk>', ReportProgressCreateView.as_view(), name='report2_create'),
    path('reportdelete/<int:pk>', ReportDeleteView.as_view(), name='report_delete'),
    path('userreportlist/<int:pk>', UserReportListView.as_view(), name='userreport_list'),
    path('reportprogressupdate/<int:pk>', ReportProgressUpdateView.as_view(), name='reportprogress_update'),
    path('reportprogresdelete/<int:pk>', ReportProgressDeleteView.as_view(), name='reportprogress_delete'),
    path('reportupdate/<int:pk>', ReportUpdateView.as_view(), name='report_update'),
    path('reportdetail/<int:pk>', PhotoCreateView.as_view(), name='report_detail'),
    path('reportlistprint', ReportListPrint.as_view(), name='report_listprint'),
    path('reportmaterialscreate/<int:pk>', ReportMaterialsCreateView.as_view(), name='reportmaterial_create'),
    path('reportmaterialsdelete/<int:pk>', ReportMaterialsDeleteView.as_view(), name='reportmaterial_delete'),
    path('usertimereportupdate/<int:pk>', UserTimeReportUpdateView.as_view(), name='usertimereport_update'),
    path('usertimereportconvert/<int:pk>', UserTimeReportConvertView.as_view(), name='usertimereport_convert'),
    path('usertimereportadd/<int:pk>', UserTimeReportAddView.as_view(), name='usertimereport_add'),
    path('search', SearchListView.as_view(), name='all_search'),
]

app/sales/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView

from .views import (ReportCreateView, ReportListView, ReportDetailView,
                    ReportDeleteView, OpportunityCreateView, OpportunityListView,
                    OpportunityDetailView, OpportunityDeleteView, update_status,
                    OpportunityTableView, OpportunityUpdateView
                    )

app_name = 'sales'

urlpatterns = [
    path('', ReportListView.as_view(), name='report_list'),
    path('reportcreate', ReportCreateView.as_view(), name='report_create'),
    path('report/<int:pk>', ReportDetailView.as_view(), name='report_detail'),
    path('report/<int:pk>/delete', ReportDeleteView.as_view(), name='report_delete'),
    path('opportunitycreate', OpportunityCreateView.as_view(), name='opportunity_create'),
    path('opportunitylist', OpportunityListView.as_view(), name='opportunity_list'),
    path('opportunitytable', OpportunityTableView.as_view(), name='opportunity_table'),
    path('opportunity/<int:pk>/update', OpportunityUpdateView.as_view(), name='opportunity_update'),
    path('opportunity/<int:pk>', OpportunityDetailView.as_view(), name='opportunity_detail'),
    path('opportunity/<int:pk>/delete', OpportunityDeleteView.as_view(), name='opportunity_delete'),
    path('update_status/<int:pk>/<int:new_status>', update_status, name='status_update')
]

app/inxcontrol/templates/__base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS CUSTOM -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <title>inxcontrol | {% block title %}{% endblock %}</title>
    <script src="{% static 'js/mainmenu.js' %}"></script>
    {% block scripts %}{% endblock %}
</head>

<body>

    {% comment %} <div class="topnav" id="myTopnav">
        <a href="#home" class="active">INX-CONTROL</a>
        <a href="{% url 'profiles:user_list' %}">Perfiles</a>
        <a href="{% url 'finances:finances_home' %}">Finanzas</a>
        <a href="{% url 'projects:project_list' %}">Proyectos</a>
        <a href="{% url 'sales:report_list' %}">Ventas</a>
        {% if perms.sales.change_report %}
            <a href="{% url 'sales:report_create' %}">Reporte</a>
        {% else %}
            <a href="{% url 'projects:report_create' %}">Reporte</a>
        {% endif %}
        <a href="javascript:void(0);" class="icon" onclick="myFunction()">
          <i class="fa fa-bars">menu</i>
        </a>
      </div> {% endcomment %}

    <!-- The sidebar -->
    <div class="sidebar" id="mySidebar">
        <a href="javascript:void(0);" class="active" onclick="myFunction()">INX-CONTROL</a>
        {% if user.is_authenticated %}
        <a href="{% url 'profiles:user_list' %}">Perfiles</a>
        {% block profiles_menu %}{% endblock%}
        <a href="{% url 'finances:finances_home' %}">Finanzas</a>
        {% block finances_menu %}{% endblock%}
        <a href="{% url 'projects:project_list' %}">Proyectos</a>
        {% block projects_menu %}{% endblock%}
        <a href="{% url 'sales:report_list' %}">Ventas</a>
        {% block sales_menu %}{% endblock%}
        {% if perms.sales.change_report %}
            <a href="{% url 'sales:report_create' %}">Reporte</a>
        {% else %}
            <a href="{% url 'projects:report_create' %}">Reporte</a>
        {% endif %}
        <form method=POST action={% url 'projects:all_search' %}>
            {% csrf_token %}
            <input class="searchbar"
            type="search"
            placeholder="Buscar"
            aria-label="Search"
            name="valuesearch">
            <button class="button" type="submit">Buscar</button>
        </form>
        {% else %}
        <a href="{% url 'profiles:login' %}">Iniciar sesión</a>
        {% endif %}
    </div>

<div class="content">
{% block content %}
{% endblock %}
</div>
{% comment %} <div class="footer">
    <div class="sitemap">
        <div>
            <h5>
                Mapa del sitio
            </h5>
            <ul>
                <li><h4>Perfiles</h4></li>
                <li><a href="{% url 'profiles:user_list' %}">Usuarios</a></li>
                <li><a href="{% url 'profiles:client_list' %}">Clientes</a></li>
                <li><a href="{% url 'profiles:supplier_list' %}">Proveedores</a></li>
                <li><a href="{% url 'profiles:workertime_lastweek' %}">Control de tiempo</a></li>
                {% if perms.finances.change_movement %}
                <li><a href="{% url 'profiles:workertime_create' %}">Pre-registro</a></li>
                {% endif %}
            </ul>
            <ul>
                <li><h4>Finanzas</h4></li>
                <li><a href="{% url 'finances:finances_home' %}">Movimientos</a></li>
                <li><a href="{% url 'finances:order_list' %}">Ordenes de compra</a></li>
                {% if perms.finances.change_movement %}
                <li><a href="{% url 'finances:finances_resume' %}">Resumen</a></li>
                <li><a href="{% url 'finances:attendance_form' %}">Asistencia</a></li>
                <li><a href="{% url 'finances:workerstime_list' %}">Horas-proyecto</a></li> 
                {% endif %}
            </ul>
            <ul>
                <li><h4>Proyectos</h4></li>
                <li><a href="{% url 'projects:project_list' %}">Proyectos</a></li>
                <li><a href="{% url 'projects:activity_list' %}">Actividades</a></li>
                <li><a href="{% url 'projects:requirement_list' %}?status=0">Requerimientos</a></li>
                <li><a href="{% url 'projects:report_list' %}">Reportes</a></li>
                <li><a class="button" href="{% url 'projects:report_create' %}">Nuevo Reporte</a></li>
            </ul>
            {% if perms.sales.change_report %}
            <ul>
                <li><h4>Ventas</h4></li>
                <li><a href="{% url 'sales:report_list' %}">Reportes</a></li>
                <li><a href="{% url 'sales:report_create' %}">Nuevo reporte</a></li>
            </ul>
            {% endif %}
        </div>
    </div>
</div> {% endcomment %}

</body>

app/inxcontrol/templates/common_menu.html
{{ svg_icon }}

app/inxcontrol/templates/search_results.html
{% extends '__base.html' %}

{% block title %}
    Resultados
{% endblock title %}

{% block content %}
{% load static %}
<h2>Resultados</h2>
<p>Resultados para "{{ searched }}"
<h5>Proyectos (en el nombre):</h5>
<div class="searchlist">
<ul>
{% for project in projects %}
<li>
    <a href="{% url 'projects:project_detail' project.pk %}">
        <img src = "{% static 'icons/icons-link.png' %}" alt="detail-icon" width="15" /></a>
    {{ project.name }}
</li>
{% endfor %}
</ul>

<h5>Actividades (en el nombre):</h5>
<ul>
{% for activity in activities %}
<li>
    <a href="{% url 'projects:activity_detail' activity.pk %}">
        <img src = "{% static 'icons/icons-link.png' %}" alt="detail-icon" width="15" /></a>
    {{ activity.name }}
</li>
{% endfor %}
</ul>

<h5>Reportes (en descripcion):</h5>
<ul>
{% for report in reports %}
<li>
    <a href="{% url 'projects:report_detail' report.pk %}">
        <img src = "{% static 'icons/icons-link.png' %}" alt="detail-icon" width="15" /></a>
    {{ report.name }}
</li>
{% endfor %}
</ul>
</div>
{% endblock content %}