app/inxcontrol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('inxcontrol/admin/', admin.site.urls),
    path('inxcontrol/profiles/', include('profiles.urls'), name='profiles'),
    path('inxcontrol/finances/', include('finances.urls'), name='finances'),
    path('inxcontrol/projects/', include('projects.urls'), name='projects'),
    path('inxcontrol/sales/', include('sales.urls'), name='sales'),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

app/profiles/urls.py
from django.urls import path, include
from .views import (UserCreateView, UserListView, UserDetailView, UserUpdateView,
                    SupplierListView, SupplierDetailView,SupplierCreateView, SupplierUpdateView,
                    ClientListView, ClientDetailView,ClientCreateView, ClientUpdateView, 
                    ClientContactUpdateView, ClientContactCreateView,  ClientContactDetailView, ClientContactListView,
                    SupplierContactUpdateView, SupplierContactCreateView,  SupplierContactDetailView, SupplierContactListView,
                    WorkerCreateView, WorkerTimeCreateView, WorkerTimeUpdateView, WorkerTimeWeekArchiveView,
                    WorkerTimeLastWeek, WorkerCostCreateView, WorkerCostUpdateView, WorkerAttendanceWeekView,
                    ClientCombineView, SupplierCategoryCreateView)

from django.contrib.auth.views import LoginView

app_name = 'profiles'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('usercreate', UserCreateView.as_view(), name='user_create'),
    path('userlist', UserListView.as_view(), name='user_list'),
    path('login', LoginView.as_view(), name='user_login'),
    path('detail/<int:pk>', UserDetailView.as_view(), name = 'user_detail'),
    path('userupdate/<int:pk>', UserUpdateView.as_view(), name='user_update'),
    path('workercreate', WorkerCreateView.as_view(), name = 'worker_create'),
    path('workertimecreate', WorkerTimeCreateView.as_view(), name='workertime_create'),
    path('workertimeupdate/<int:pk>', WorkerTimeUpdateView.as_view(), name='workertime_update'),
    path(
        'workertime/<int:year>/week/<int:week>',
        WorkerTimeWeekArchiveView.as_view(),
        name='workertime_week'
    ),
    path(
        # Reporte de asistencia de trabajadores con indicacion de reportes faltantes
        'workersattendance/<str:inicio>/<str:final>/<str:extra>/<str:adicional>/<str:cliente>',
        WorkerAttendanceWeekView.as_view(),
        name='workerattendance_week',
    ),
    path('workertime/last', WorkerTimeLastWeek.as_view(), name='workertime_lastweek'),
    path('workercostcreate/<int:pk>', WorkerCostCreateView.as_view(), name='workercost_create'),
    path('workercostupdate/<int:pk>', WorkerCostUpdateView.as_view(), name='workercost_update'),
    path('clientcreate', ClientCreateView.as_view(), name='client_create'),
    path('clientlist', ClientListView.as_view(), name = 'client_list'),
    path('clientdetail/<int:pk>', ClientDetailView.as_view(), name='client_detail'),
    path('clientupdate/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('suppliercreate', SupplierCreateView.as_view(), name='supplier_create'),
    path('supplierlist', SupplierListView.as_view(), name='supplier_list'),
    path('supplierdetail/<int:pk>', SupplierDetailView.as_view(), name='supplier_detail'),
    path('supplierupdate/<int:pk>', SupplierUpdateView.as_view(), name='supplier_update'),
    path('clientcontactcreate', ClientContactCreateView.as_view(), name='clientcontact_create'),
    path('clientcontactlist', ClientContactListView.as_view(), name = 'clientcontact_list'),
    path('clientcontactdetail/<int:pk>', ClientContactDetailView.as_view(), name='clientcontact_detail'),
    path('clientcontactupdate/<int:pk>', ClientContactUpdateView.as_view(), name='clientcontact_update'),
    path('clientcombination', ClientCombineView.as_view(), name='client_combination'),
    path('suppliercontactcreate', SupplierContactCreateView.as_view(), name='suppliercontact_create'),
    path('suppliercontactlist', SupplierContactListView.as_view(), name = 'suppliercontact_list'),
    path('suppliercontactdetail/<int:pk>', SupplierContactDetailView.as_view(), name='suppliercontact_detail'),
    path('suppliercontactupdate/<int:pk>', SupplierContactUpdateView.as_view(), name='suppliercontact_update'),
    path('suppliercategorycreate', SupplierCategoryCreateView.as_view(), name='suppliercategory_create'),
]

app/projects/urls.py
from django.urls import path

from .views import ( ProjectCreateView, ProjectListView, ProjectDetailView,
                     ProjectUpdateView, ActivityCreateView, ActivityDetailView,
                     ActivityListView, RequirementCreateView, RequirementListView,
                     ReportCreateView, ReportListView, ReportUpdateView, ActivityUpdateView,
                     ReportDetailView, PhotoCreateView, RequirementUpdateView,
                     ActivityDeleteView, ActivityCompactListView, ReportCardListView,
                     ActivityProgressCreateView, ReportProgressCreateView,
                     ActivityProgressUpdateView, ReportProgressUpdateView,
                     ReportProgressDeleteView, ActivityProgressDeleteView, SearchListView,
                     ReportDeleteView, ReportDayArchiveView, ReportLastdayArchiveView,
                     ActivityPrintView, RequirementCompleteView, ProjectCostUpdateView,
                     ProjectDeleteView, ReportMaterialsCreateView, ReportMaterialsDeleteView,
                     ReportListPrint, ActivityReportView, UserTimeReportUpdateView,
                     UserTimeReportConvertView, UserTimeReportAddView, ActivityWorkingListView,
                     UserReportListView )
app_name = 'projects'

urlpatterns = [
    path('projectlist', ProjectListView.as_view(), name='project_list' ),
    path('projectcreate', ProjectCreateView.as_view(),name='project_create'),
    path('projectdelete/<int:pk>', ProjectDeleteView.as_view(),name='project_delete'),
    path("projectdetail/<int:pk>", ProjectDetailView.as_view(), name = 'project_detail'),
    path('projectupdate/<int:pk>', ProjectUpdateView.as_view(), name='project_update' ),
    path('projectcostupdate/<int:pk>', ProjectCostUpdateView.as_view(), name='projectcost_update' ),
    path('activitylist', ActivityListView.as_view(), name='activity_list'),
    path('activityprint', ActivityPrintView.as_view(), name='activity_print'),
    path('activitycompactlist', ActivityCompactListView.as_view(), name='activity_compactlist'),
    path('activitycreate', ActivityCreateView.as_view(), name='activity_create'),
    path('activitydetail/<int:pk>', ActivityDetailView.as_view(), name='activity_detail'),
    path('activityupdate/<int:pk>', ActivityUpdateView.as_view(), name='activity_update'),
    path('activitydelete/<int:pk>', ActivityDeleteView.as_view(), name='activity_delete'),
    path('activityworkinglist', ActivityWorkingListView.as_view(), name='activity_workinglist'),
    path('activityreport', ActivityReportView.as_view(), name='activity_report'),
    path('activityprogresscreate/<int:pk>', ActivityProgressCreateView.as_view(), name='activityprogress_create'),
    path('activityprogressupdate/<int:pk>', ActivityProgressUpdateView.as_view(), name='activityprogress_update'),
    path('activityprogressdelete/<int:pk>', ActivityProgressDeleteView.as_view(), name='activityprogress_delete'),
    path('requirementcreate', RequirementCreateView.as_view(), name='requirement_create'),
    path('requirementupdate/<int:pk>', RequirementUpdateView.as_view(), name='requirement_update'),
    path('requirementlist', RequirementListView.as_view(), name='requirement_list'),
    path('requirementcomplete/<int:pk>', RequirementCompleteView.as_view(), name='requirement_complete'),
    path('reportlist', ReportListView.as_view(), name='report_list'),
    path('reports/lastday', ReportLastdayArchiveView.as_view(), name='report_lastday'),
    path('reports/<int:year>/<str:month>/<int:day>/', ReportDayArchiveView.as_view(), name='report_dayarchive'),
    path('reportcardlist', ReportCardListView.as_view(), name='report_cardlist'),
    path('reportcreate', ReportCreateView.as_view(), name='report_create'),
    path('reportcreate/<int:pk>', ReportProgressCreateView.as_view(), name='report2_create'),
    path('reportdelete/<int:pk>', ReportDeleteView.as_view(), name='report_delete'),
    path('userreportlist/<int:pk>', UserReportListView.as_view(), name='userreport_list'),
    path('reportprogressupdate/<int:pk>', ReportProgressUpdateView.as_view(), name='reportprogress_update'),
    path('reportprogresdelete/<int:pk>', ReportProgressDeleteView.as_view(), name='reportprogress_delete'),
    path('reportupdate/<int:pk>', ReportUpdateView.as_view(), name='report_update'),
    path('reportdetail/<int:pk>', PhotoCreateView.as_view(), name='report_detail'),
    path('reportlistprint', ReportListPrint.as_view(), name='report_listprint'),
    path('reportmaterialscreate/<int:pk>', ReportMaterialsCreateView.as_view(), name='reportmaterial_create'),
    path('reportmaterialsdelete/<int:pk>', ReportMaterialsDeleteView.as_view(), name='reportmaterial_delete'),
    path('usertimereportupdate/<int:pk>', UserTimeReportUpdateView.as_view(), name='usertimereport_update'),
    path('usertimereportconvert/<int:pk>', UserTimeReportConvertView.as_view(), name='usertimereport_convert'),
    path('usertimereportadd/<int:pk>', UserTimeReportAddView.as_view(), name='usertimereport_add'),
    path('search', SearchListView.as_view(), name='all_search'),
]

app/sales/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView

from .views import (ReportCreateView, ReportListView, ReportDetailView,
                    ReportDeleteView, OpportunityCreateView, OpportunityListView,
                    OpportunityDetailView, OpportunityDeleteView, update_status,
                    OpportunityTableView, OpportunityUpdateView
                    )

app_name = 'sales'

urlpatterns = [
    path('', ReportListView.as_view(), name='report_list'),
    path('reportcreate', ReportCreateView.as_view(), name='report_create'),
    path('report/<int:pk>', ReportDetailView.as_view(), name='report_detail'),
    path('report/<int:pk>/delete', ReportDeleteView.as_view(), name='report_delete'),
    path('opportunitycreate', OpportunityCreateView.as_view(), name='opportunity_create'),
    path('opportunitylist', OpportunityListView.as_view(), name='opportunity_list'),
    path('opportunitytable', OpportunityTableView.as_view(), name='opportunity_table'),
    path('opportunity/<int:pk>/update', OpportunityUpdateView.as_view(), name='opportunity_update'),
    path('opportunity/<int:pk>', OpportunityDetailView.as_view(), name='opportunity_detail'),
    path('opportunity/<int:pk>/delete', OpportunityDeleteView.as_view(), name='opportunity_delete'),
    path('update_status/<int:pk>/<int:new_status>', update_status, name='status_update')
]

app/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import datetime

class Contact(models.Model):
    """
    Modelo para datos de contactos que no son usuarios
    """
    name = models.CharField(
        max_length=127,
        help_text="Nombre del contacto",
    )
    phone = models.CharField(
        max_length=16,
        help_text="Telefono del contacto",
        blank=True,
        null = True,
    )
    notes = models.TextField(
        max_length=511,
        help_text="Notas del contacto",
        blank=True,
        null = True,
    )

    class Meta:
        abstract = True

    def __str__(self):
        return self.name

class Client(models.Model):
    """
    Modelo para los clientes
    """
    class Status(models.IntegerChoices):
        ACTIVO = 0, ("Activo")
        INACTIVO = 1, ("Inactivo")

    name = models.CharField(
        max_length=127,
        help_text="Nombre del cliente"
    )
    status = models.IntegerField(
        choices=Status.choices,
        default=0,
        help_text="Estado actual del cliente"
    )
    score = models.IntegerField(
        default=10,
        help_text="Calificación del cliente"
    )

    def __str__(self):
        return f"{self.name}"
    
class ClientContact(Contact):
    client = models.ForeignKey(
        Client,
        on_delete=models.CASCADE,
        help_text="Cliente asignado"
    )
    
class Supplier(models.Model):
    """
    Modelo para los proveedores, gregresar orden por categoria
    """
    name = models.CharField(
        max_length=127,
        help_text="Nombre del proveedor"
    )
    category = models.ForeignKey(
        'SupplierCategory',
        on_delete=models.CASCADE,
        null = True,
        blank = True,
        help_text="Categoria del proveedor"
    )

    def __str__(self):
        return '{}: {}'.format(self.category, self.name)
    
    class Meta:
        ordering = ['category']

class SupplierContact(Contact):
    supplier = models.ForeignKey(
        Supplier,
        on_delete=models.CASCADE,
        help_text="Proveedor asignado"
    )

class SupplierCategory(models.Model):
    name = models.CharField(
        max_length=127,
        help_text="Nombre de la categoria"
    )

    def __str__(self):
        return self.name

class WorkersTime(models.Model):
    workdate = models.DateField(
        default = datetime.now,
        blank=True,
        null = True,
    )
    worker = models.ManyToManyField(
        User,
        help_text= "Trabajador asignado"
    )
    client = models.ForeignKey(
        Client, 
        on_delete = models.CASCADE,
        help_text = "Cliente al cual esta asignado"
    )

class WorkerCost(models.Model):
    worker = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True
    )
    normal_cost = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Costo normal por hora"
    )
    extra_cost = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Costo extra por hora"
    )

app/profiles/templates/profiles/client_combine.html
{% extends '__base.html' %}

{%block title %}Combinar proyectos de clientes{% endblock %}

{% block profiles_menu %}
<ul>
    <li><a href="{% url 'profiles:user_list' %}">Usuarios</a></li>
    <li><a href="{% url 'profiles:client_list' %}">Clientes</a></li>
    <li><a href="{% url 'profiles:supplier_list' %}">Proveedores</a></li>
    <li><a href="{% url 'profiles:workertime_lastweek' %}">Control de tiempo</a></li>
    {% if perms.finances.change_movement %}
    <li><a href="{% url 'profiles:workertime_create' %}">Pre-registro</a></li>
    {% endif %}
</ul>
{% endblock%}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Registrar">
</form>
{% endblock %}

app/profiles/templates/profiles/client_detail.html
{% extends '__base.html' %}
{% load static %}
{%block title %}Detalle de cliente{% endblock %}

{% block profiles_menu %}
<ul>
    <li><a href="{% url 'profiles:user_list' %}">Usuarios</a></li>
    <li><a href="{% url 'profiles:client_list' %}">Clientes</a></li>
    <li><a href="{% url 'profiles:supplier_list' %}">Proveedores</a></li>
    <li><a href="{% url 'profiles:workertime_lastweek' %}">Control de tiempo</a></li>
    {% if perms.finances.change_movement %}
    <li><a href="{% url 'profiles:workertime_create' %}">Pre-registro</a></li>
    {% endif %}
</ul>
{% endblock%}

{% block content %}
<ul>
    <li>ID: {{ client.pk }}</li>
    <li>Nombre: {{ client.name }}</li>
    <li>Estado: {{ client.get_status_display }}</li>
    <li>Calificacion: {{ client.score }}</li>
    <li>Contactos:
        <ul>
            {% for contact in client.clientcontact_set.all %}
            <li>{{ contact }} | tel: {{ contact.phone }}</li>
            {% endfor %}
        </ul>
    </li>
</ul>
<table class="project-table">
    <thead>
        <tr>
            <th>Proyectos Activos</th>
        </tr>
    </thead>
    {% comment %}
    Get all active projects related to this client and show them
    {% endcomment %}
    
    {% for project in client.project_client.all %}
    {% if project.status == 0 %}
        <tr>
            <td>
                {{ project.name }}
                <a href="{% url 'projects:project_detail' project.id %}">
                    <img src = "{% static 'icons/icons-link.png' %}" alt="detail-icon" width="15" />
                </a>
            </td>
        </tr>
    {% endif %}
    {% endfor %}
</table>

<a class="button" href="{% url 'profiles:clientcontact_create' %}?client={{client.pk}}">Agregar contacto</a>
<a class="button" href="{% url 'profiles:client_update' client.pk %}">Editar</a>
{% endblock %}

app/profiles/templates/profiles/clientcontact_detail.html
{% extends '__base.html' %}

{%block title %}Detalle de contacto{% endblock %}

{% block profiles_menu %}
<ul>
    <li><a href="{% url 'profiles:user_list' %}">Usuarios</a></li>
    <li><a href="{% url 'profiles:client_list' %}">Clientes</a></li>
    <li><a href="{% url 'profiles:supplier_list' %}">Proveedores</a></li>
    <li><a href="{% url 'profiles:workertime_lastweek' %}">Control de tiempo</a></li>
    {% if perms.finances.change_movement %}
    <li><a href="{% url 'profiles:workertime_create' %}">Pre-registro</a></li>
    {% endif %}
</ul>
{% endblock%}

{% block content %}
<p>
{{ clientcontact.pk }}
</p>
<p>
{{ clientcontact.name }}
</p>
<p>
{{ clientcontact.phone }}
</p>
<p>
{{ clientcontact.client }}
</p>
<p>
{{ clientcontact.notes }}
</p>
<a href="{% url 'profiles:clientcontact_update' clientcontact.pk %}">editar</a>
{% endblock %}

app/profiles/templates/profiles/clientcontact_list.html
{% extends '__base.html' %}

{%block title %}Lista de contactos{% endblock %}

{% block profiles_menu %}
<ul>
    <li><a href="{% url 'profiles:user_list' %}">Usuarios</a></li>
    <li><a href="{% url 'profiles:client_list' %}">Clientes</a></li>
    <li><a href="{% url 'profiles:supplier_list' %}">Proveedores</a></li>
    <li><a href="{% url 'profiles:workertime_lastweek' %}">Control de tiempo</a></li>
    {% if perms.finances.change_movement %}
    <li><a href="{% url 'profiles:workertime_create' %}">Pre-registro</a></li>
    {% endif %}
</ul>
{% endblock%}

{% block content %}
<table class="project-table">
    <thead class="table">
        <tr>
            <th scope="col">Contacto</th>
            <th scope="col">Cliente</th>
        </tr>
    </thead>
    {% for contact in clientcontact_list %}
    <tr>
        <td scope="row"><a href = "{% url 'profiles:clientcontact_detail' contact.pk %}">{{contact}}</a></td>
        <td scope="row">{{contact.client}} </td>
    </tr>
    {% endfor %}
    <tr>
        <td colspan="2"><a href="{% url 'profiles:clientcontact_create' %}">Crear contacto</a></td>
    </tr>
</table>

{% endblock %}

app/profiles/templates/profiles/supplier_detail.html
{% extends '__base.html' %}

{%block title %}Detalle de proveedor{% endblock %}

{% block profiles_menu %}
<ul>
    <li><a href="{% url 'profiles:user_list' %}">Usuarios</a></li>
    <li><a href="{% url 'profiles:client_list' %}">Clientes</a></li>
    <li><a href="{% url 'profiles:supplier_list' %}">Proveedores</a></li>
    <li><a href="{% url 'profiles:workertime_lastweek' %}">Control de tiempo</a></li>
    {% if perms.finances.change_movement %}
    <li><a href="{% url 'profiles:workertime_create' %}">Pre-registro</a></li>
    {% endif %}
</ul>
{% endblock%}

{% block content %}
<table class="project-table">
    <tr>
        <td>ID:</td>
        <td>{{ supplier.pk }}</td>
    </tr>
    <tr>
        <td>Nombre:</td>
        <td>{{ supplier.name }}</td>
    </tr>
    <tr>
        <td colspan="2">Contactos del proveedor</td>
    </tr>
    <tr>        <td colspan="2">
            <table class="project-table">
                {% for contact in supplier.suppliercontact_set.all %}
                <tr>
                    <td>{{ contact.name }}</td>
                    <td>{{ contact.phone }}</td>
                </tr>
                {% endfor %}
            </table>
        </td>
    </tr>
</table>

<a class="button" href="{% url 'profiles:suppliercontact_create' %}">agregar contacto</a> |
<a class="button" href="{% url 'profiles:supplier_update' supplier.pk %}">editar</a>
{% endblock %}

app/profiles/templates/profiles/supplier_list.html
{% extends '__base.html' %}

{%block title %}Lista de proveedores{% endblock %}

{% block profiles_menu %}
<ul>
    <li><a href="{% url 'profiles:user_list' %}">Usuarios</a></li>
    <li><a href="{% url 'profiles:client_list' %}">Clientes</a></li>
    <li><a href="{% url 'profiles:supplier_list' %}">Proveedores</a></li>
    <li><a href="{% url 'profiles:workertime_lastweek' %}">Control de tiempo</a></li>
    {% if perms.finances.change_movement %}
    <li><a href="{% url 'profiles:workertime_create' %}">Pre-registro</a></li>
    {% endif %}
</ul>
{% endblock%}

{% block content %}
{% load static %}
<div class="resp-table">
    <div class="resp-table-header">
        <div class="table-header-cell">ID</div>
        <div class="table-header-cell">Proveedor</div>
        <div class="table-header-cell">Categoria</div>
        <div class="table-header-cell">Acciones</div>
    </div>
    <div class="resp-table-body">
        {% for supplier in supplier_list %}
        <div class="resp-table-row">
            <div class="table-body-id-cell">{{supplier.pk}}</div>
            <div class="table-body-cell">{{supplier}}</div>
            <div class="table-body-cell">{{supplier.category}}</div>
            <div class="table-body-action-cell">
                <a href="{% url 'profiles:supplier_detail' supplier.pk %}">
                    <img src = "{% static 'icons/icons-link.png' %}" alt="detail-icon" width="15" /></a>
                <a href="{% url 'profiles:supplier_update' supplier.pk %}">
                    <img src = "{% static 'icons/icons-edit.svg' %}" alt="edit-icon"/></a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class="action-buttons">
    <a class="button" href="{% url 'profiles:supplier_create' %}">Nuevo proveedor</a>
    <a class="button" href="{% url 'profiles:suppliercontact_list' %}">Contactos de proveedores</a>
    <a class="button" href="{% url 'profiles:suppliercategory_create' %}">Nueva categoria</a>
</div>

{% endblock %}

app/profiles/templates/profiles/suppliercontact_list.html
{% extends '__base.html' %}

{%block title %}Lista de contactos{% endblock %}

{% block profiles_menu %}
<ul>
    <li><a href="{% url 'profiles:user_list' %}">Usuarios</a></li>
    <li><a href="{% url 'profiles:client_list' %}">Clientes</a></li>
    <li><a href="{% url 'profiles:supplier_list' %}">Proveedores</a></li>
    <li><a href="{% url 'profiles:workertime_lastweek' %}">Control de tiempo</a></li>
    {% if perms.finances.change_movement %}
    <li><a href="{% url 'profiles:workertime_create' %}">Pre-registro</a></li>
    {% endif %}
</ul>
{% endblock%}

{% block content %}
<table class="project-table">
    <thead class="table">
        <tr>
            <th scope="col">Contacto</th>
            <th scope="col">Proveedor</th>
        </tr>
    </thead>
    {% for contact in suppliercontact_list %}
    <tr>
        <td scope="row"><a href = "{% url 'profiles:suppliercontact_detail' contact.pk %}">{{contact}}</a></td>
        <td scope="row">{{contact.supplier}}</td>
    </tr>
    {% endfor %}
    <tr>
        <td colspan="2"><a href="{% url 'profiles:suppliercontact_create' %}">Crear</a></td>
    </tr>
</table>

{% endblock %}

app/profiles/templates/profiles/workerstime_archive_week.html
{% extends '__base.html' %}

{%block title %}Registros de tiempo{% endblock %}

{% block profiles_menu %}
<ul>
    <li><a href="{% url 'profiles:user_list' %}">Usuarios</a></li>
    <li><a href="{% url 'profiles:client_list' %}">Clientes</a></li>
    <li><a href="{% url 'profiles:supplier_list' %}">Proveedores</a></li>
    <li><a href="{% url 'profiles:workertime_lastweek' %}">Control de tiempo</a></li>
    {% if perms.finances.change_movement %}
    <li><a href="{% url 'profiles:workertime_create' %}">Pre-registro</a></li>
    {% endif %}
</ul>
{% endblock%}

{% block content %}
{% load static %}

<div class="resp-table">
    <div class="resp-table-header">
        <div class="table-header-cell">Proyecto | Actividad</div>
        {% for week_date in week_dates %}
        <div class="table-header-cell">{{week_date|date:'Y-m-d'}}</div>
        {% endfor %}
    </div>
    <div class="resp-table-body">
        {% for day in calendar_table %}
            <div class="resp-table-cal-row">
            {% for activity in day %}
                    {% if activity.id %}
                        <div class="table-body-id-cell">
                            {{ activity.project }}</br>
                            {{ activity.name }}
                        </div>
                    {% else %}
                    <div class="table-body-cal-cell">
                        <ul>
                        {% for report in activity %}
                        ID:{{report.pk}}, Horas: {{ report.duration }}
                            <a href="{% url 'projects:report_detail' report.pk %}">
                                <img src = "{% static 'icons/icons-link.png' %}" alt="detail-icon" width="15" /></a>
                            <a href="{% url 'projects:report_update' report.pk %}">
                                <img src = "{% static 'icons/icons-edit.svg' %}" alt="edit-icon"/></a>
                            {% for worker in report.workers.all %}
                                <li>{{ worker.last_name }}, {{ worker.first_name}}</li>
                            {% endfor %}
                        {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
            {% endfor %}
            </div>
        {% endfor %}
    </div>
</div>
        {% if previous_week %}
        <a class="button" href="{% url 'profiles:workertime_week' previous_week|date:'Y' previous_week|date:'W' %}">
            Año: {{ previous_week|date:'Y' }} Semana: {{ previous_week|date:'W' }}
        </a>
        {% endif %}
        {% if next_week %}
        <a class="button" href="{% url 'profiles:workertime_week' next_week|date:'Y' next_week|date:'W' %}">
        Año: {{ next_week|date:'Y' }} Semana: {{ next_week|date:'W' }}
        </a>
        {% endif %}
{% endblock %}