app/finances/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required
from finances.views import (MovementCreateView, MovementUpdateView, MovementDeleteView,
                            MovementMontArchiveView,MovementLastMonth ,MovementAdminListView,
                            WorkersTimeListView, AttendanceReport, AttendanceReportFormClass,
                            AttendaceFullReportClass, UserAccountingTemplateView,
                            ProjectAttendanceReport, OrderCreateView, OrderListView,
                            OrderDetailView, OrderUpdateView, order_complete)

app_name = 'finances'

urlpatterns = [
    path('', MovementCreateView.as_view(), name = 'finances_home'),
    path('currentmonth',MovementLastMonth.as_view(), name='finances_lastmonth'),
    path('movementlist/<int:year>/<int:month>', MovementMontArchiveView.as_view(), name='finances_month'),
    path('movementresume', UserAccountingTemplateView.as_view(), name='finances_resume'),
    path('edit/<int:pk>', MovementUpdateView.as_view(), name = 'finances_edit'),
    path('delete/<int:pk>', MovementDeleteView.as_view(), name='finances_delete'),
    path('workerstime', WorkersTimeListView.as_view(), name='workerstime_list'),
    #path('attendance', AttendanceReport.as_view(), name='attendance_report'),
    path(
        'attendance/<str:inicio>/<str:final>/<str:extra>/<str:adicional>/<str:cliente>',
        AttendaceFullReportClass.as_view(),
        name='attendance_report'),
    path(
        # Formulario para generar reporte de asistencia
        'attendanceform',
        AttendanceReportFormClass.as_view(),
        name='attendance_form',
    ),
    path(
        'projectattendance/<int:pk>',
        ProjectAttendanceReport.as_view(),
        name='projectattendance_report'
    ),
    # path(
    #     'projectattendance/<int:pk>',
    #     permission_required('finances.change_movement')(ProjectAttendanceReport.as_view()),
    #     name = 'projectattendance_report'
    # ),
    path(
        'ordercreate',
        OrderCreateView.as_view(),
        name='order_create',
    ),
    path(
        'orderlist',
        OrderListView.as_view(),
        name = 'order_list',
    ),
    path(
        'orderdetail/<int:pk>',
        OrderDetailView.as_view(),
        name = 'order_detail',
    ),
    path(
        'orderupdate/<int:pk>',
        OrderUpdateView.as_view(),
        name = 'order_update',
    ),
    path(
        'ordercomplete/<int:pk>',
        order_complete,
        name = 'order_complete',
    )
]

app/inxcontrol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('inxcontrol/admin/', admin.site.urls),
    path('inxcontrol/profiles/', include('profiles.urls'), name='profiles'),
    path('inxcontrol/finances/', include('finances.urls'), name='finances'),
    path('inxcontrol/projects/', include('projects.urls'), name='projects'),
    path('inxcontrol/sales/', include('sales.urls'), name='sales'),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

app/profiles/urls.py
from django.urls import path, include
from .views import (UserCreateView, UserListView, UserDetailView, UserUpdateView,
                    SupplierListView, SupplierDetailView,SupplierCreateView, SupplierUpdateView,
                    ClientListView, ClientDetailView,ClientCreateView, ClientUpdateView, 
                    ClientContactUpdateView, ClientContactCreateView,  ClientContactDetailView, ClientContactListView,
                    SupplierContactUpdateView, SupplierContactCreateView,  SupplierContactDetailView, SupplierContactListView,
                    WorkerCreateView, WorkerTimeCreateView, WorkerTimeUpdateView, WorkerTimeWeekArchiveView,
                    WorkerTimeLastWeek, WorkerCostCreateView, WorkerCostUpdateView, WorkerAttendanceWeekView,
                    ClientCombineView, SupplierCategoryCreateView)

from django.contrib.auth.views import LoginView

app_name = 'profiles'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('usercreate', UserCreateView.as_view(), name='user_create'),
    path('userlist', UserListView.as_view(), name='user_list'),
    path('login', LoginView.as_view(), name='user_login'),
    path('detail/<int:pk>', UserDetailView.as_view(), name = 'user_detail'),
    path('userupdate/<int:pk>', UserUpdateView.as_view(), name='user_update'),
    path('workercreate', WorkerCreateView.as_view(), name = 'worker_create'),
    path('workertimecreate', WorkerTimeCreateView.as_view(), name='workertime_create'),
    path('workertimeupdate/<int:pk>', WorkerTimeUpdateView.as_view(), name='workertime_update'),
    path(
        'workertime/<int:year>/week/<int:week>',
        WorkerTimeWeekArchiveView.as_view(),
        name='workertime_week'
    ),
    path(
        # Reporte de asistencia de trabajadores con indicacion de reportes faltantes
        'workersattendance/<str:inicio>/<str:final>/<str:extra>/<str:adicional>/<str:cliente>',
        WorkerAttendanceWeekView.as_view(),
        name='workerattendance_week',
    ),
    path('workertime/last', WorkerTimeLastWeek.as_view(), name='workertime_lastweek'),
    path('workercostcreate/<int:pk>', WorkerCostCreateView.as_view(), name='workercost_create'),
    path('workercostupdate/<int:pk>', WorkerCostUpdateView.as_view(), name='workercost_update'),
    path('clientcreate', ClientCreateView.as_view(), name='client_create'),
    path('clientlist', ClientListView.as_view(), name = 'client_list'),
    path('clientdetail/<int:pk>', ClientDetailView.as_view(), name='client_detail'),
    path('clientupdate/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('suppliercreate', SupplierCreateView.as_view(), name='supplier_create'),
    path('supplierlist', SupplierListView.as_view(), name='supplier_list'),
    path('supplierdetail/<int:pk>', SupplierDetailView.as_view(), name='supplier_detail'),
    path('supplierupdate/<int:pk>', SupplierUpdateView.as_view(), name='supplier_update'),
    path('clientcontactcreate', ClientContactCreateView.as_view(), name='clientcontact_create'),
    path('clientcontactlist', ClientContactListView.as_view(), name = 'clientcontact_list'),
    path('clientcontactdetail/<int:pk>', ClientContactDetailView.as_view(), name='clientcontact_detail'),
    path('clientcontactupdate/<int:pk>', ClientContactUpdateView.as_view(), name='clientcontact_update'),
    path('clientcombination', ClientCombineView.as_view(), name='client_combination'),
    path('suppliercontactcreate', SupplierContactCreateView.as_view(), name='suppliercontact_create'),
    path('suppliercontactlist', SupplierContactListView.as_view(), name = 'suppliercontact_list'),
    path('suppliercontactdetail/<int:pk>', SupplierContactDetailView.as_view(), name='suppliercontact_detail'),
    path('suppliercontactupdate/<int:pk>', SupplierContactUpdateView.as_view(), name='suppliercontact_update'),
    path('suppliercategorycreate', SupplierCategoryCreateView.as_view(), name='suppliercategory_create'),
]

app/projects/urls.py
from django.urls import path

from .views import ( ProjectCreateView, ProjectListView, ProjectDetailView,
                     ProjectUpdateView, ActivityCreateView, ActivityDetailView,
                     ActivityListView, RequirementCreateView, RequirementListView,
                     ReportCreateView, ReportListView, ReportUpdateView, ActivityUpdateView,
                     ReportDetailView, PhotoCreateView, RequirementUpdateView,
                     ActivityDeleteView, ActivityCompactListView, ReportCardListView,
                     ActivityProgressCreateView, ReportProgressCreateView,
                     ActivityProgressUpdateView, ReportProgressUpdateView,
                     ReportProgressDeleteView, ActivityProgressDeleteView, SearchListView,
                     ReportDeleteView, ReportDayArchiveView, ReportLastdayArchiveView,
                     ActivityPrintView, RequirementCompleteView, ProjectCostUpdateView,
                     ProjectDeleteView, ReportMaterialsCreateView, ReportMaterialsDeleteView,
                     ReportListPrint, ActivityReportView, UserTimeReportUpdateView,
                     UserTimeReportConvertView, UserTimeReportAddView, ActivityWorkingListView,
                     UserReportListView )
app_name = 'projects'

urlpatterns = [
    path('projectlist', ProjectListView.as_view(), name='project_list' ),
    path('projectcreate', ProjectCreateView.as_view(),name='project_create'),
    path('projectdelete/<int:pk>', ProjectDeleteView.as_view(),name='project_delete'),
    path("projectdetail/<int:pk>", ProjectDetailView.as_view(), name = 'project_detail'),
    path('projectupdate/<int:pk>', ProjectUpdateView.as_view(), name='project_update' ),
    path('projectcostupdate/<int:pk>', ProjectCostUpdateView.as_view(), name='projectcost_update' ),
    path('activitylist', ActivityListView.as_view(), name='activity_list'),
    path('activityprint', ActivityPrintView.as_view(), name='activity_print'),
    path('activitycompactlist', ActivityCompactListView.as_view(), name='activity_compactlist'),
    path('activitycreate', ActivityCreateView.as_view(), name='activity_create'),
    path('activitydetail/<int:pk>', ActivityDetailView.as_view(), name='activity_detail'),
    path('activityupdate/<int:pk>', ActivityUpdateView.as_view(), name='activity_update'),
    path('activitydelete/<int:pk>', ActivityDeleteView.as_view(), name='activity_delete'),
    path('activityworkinglist', ActivityWorkingListView.as_view(), name='activity_workinglist'),
    path('activityreport', ActivityReportView.as_view(), name='activity_report'),
    path('activityprogresscreate/<int:pk>', ActivityProgressCreateView.as_view(), name='activityprogress_create'),
    path('activityprogressupdate/<int:pk>', ActivityProgressUpdateView.as_view(), name='activityprogress_update'),
    path('activityprogressdelete/<int:pk>', ActivityProgressDeleteView.as_view(), name='activityprogress_delete'),
    path('requirementcreate', RequirementCreateView.as_view(), name='requirement_create'),
    path('requirementupdate/<int:pk>', RequirementUpdateView.as_view(), name='requirement_update'),
    path('requirementlist', RequirementListView.as_view(), name='requirement_list'),
    path('requirementcomplete/<int:pk>', RequirementCompleteView.as_view(), name='requirement_complete'),
    path('reportlist', ReportListView.as_view(), name='report_list'),
    path('reports/lastday', ReportLastdayArchiveView.as_view(), name='report_lastday'),
    path('reports/<int:year>/<str:month>/<int:day>/', ReportDayArchiveView.as_view(), name='report_dayarchive'),
    path('reportcardlist', ReportCardListView.as_view(), name='report_cardlist'),
    path('reportcreate', ReportCreateView.as_view(), name='report_create'),
    path('reportcreate/<int:pk>', ReportProgressCreateView.as_view(), name='report2_create'),
    path('reportdelete/<int:pk>', ReportDeleteView.as_view(), name='report_delete'),
    path('userreportlist/<int:pk>', UserReportListView.as_view(), name='userreport_list'),
    path('reportprogressupdate/<int:pk>', ReportProgressUpdateView.as_view(), name='reportprogress_update'),
    path('reportprogresdelete/<int:pk>', ReportProgressDeleteView.as_view(), name='reportprogress_delete'),
    path('reportupdate/<int:pk>', ReportUpdateView.as_view(), name='report_update'),
    path('reportdetail/<int:pk>', PhotoCreateView.as_view(), name='report_detail'),
    path('reportlistprint', ReportListPrint.as_view(), name='report_listprint'),
    path('reportmaterialscreate/<int:pk>', ReportMaterialsCreateView.as_view(), name='reportmaterial_create'),
    path('reportmaterialsdelete/<int:pk>', ReportMaterialsDeleteView.as_view(), name='reportmaterial_delete'),
    path('usertimereportupdate/<int:pk>', UserTimeReportUpdateView.as_view(), name='usertimereport_update'),
    path('usertimereportconvert/<int:pk>', UserTimeReportConvertView.as_view(), name='usertimereport_convert'),
    path('usertimereportadd/<int:pk>', UserTimeReportAddView.as_view(), name='usertimereport_add'),
    path('search', SearchListView.as_view(), name='all_search'),
]

app/sales/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView

from .views import (ReportCreateView, ReportListView, ReportDetailView,
                    ReportDeleteView, OpportunityCreateView, OpportunityListView,
                    OpportunityDetailView, OpportunityDeleteView, update_status,
                    OpportunityTableView, OpportunityUpdateView
                    )

app_name = 'sales'

urlpatterns = [
    path('', ReportListView.as_view(), name='report_list'),
    path('reportcreate', ReportCreateView.as_view(), name='report_create'),
    path('report/<int:pk>', ReportDetailView.as_view(), name='report_detail'),
    path('report/<int:pk>/delete', ReportDeleteView.as_view(), name='report_delete'),
    path('opportunitycreate', OpportunityCreateView.as_view(), name='opportunity_create'),
    path('opportunitylist', OpportunityListView.as_view(), name='opportunity_list'),
    path('opportunitytable', OpportunityTableView.as_view(), name='opportunity_table'),
    path('opportunity/<int:pk>/update', OpportunityUpdateView.as_view(), name='opportunity_update'),
    path('opportunity/<int:pk>', OpportunityDetailView.as_view(), name='opportunity_detail'),
    path('opportunity/<int:pk>/delete', OpportunityDeleteView.as_view(), name='opportunity_delete'),
    path('update_status/<int:pk>/<int:new_status>', update_status, name='status_update')
]

app/finances/models.py
from django.db import models
from django.contrib.auth.models import User
from profiles.models import Supplier
from projects.models import Activity
from datetime import datetime

import os

class Movement(models.Model):
    payee = models.ForeignKey(
        Supplier,
        models.SET_NULL,
        blank = True,
        null = True
    )
    creation_date = models.DateField(
        default = datetime.now,
    )
    description = models.CharField(
        max_length=254
    )
    amount = models.DecimalField(
        decimal_places=3,
        max_digits=7
    )
    no_invoice = models.BooleanField(
        blank = True,
        default = False
    )
    payment = models.BooleanField(
        blank = True,
        default = False
    )
    responsable = models.ForeignKey(
        User,
        models.CASCADE
    )
    files = models.FileField(
        upload_to="finances/%Y/%m/%d/",
        blank = True,
        null = True
    )

class Order(models.Model):
    class status(models.IntegerChoices):
        NEW = 1, ('Nueva')
        TO_BE_APPROVED = 2, ('Por aprobar')
        TO_BE_PAIED = 3, ('Por pagar')
        NOTIFY_PROVIDER = 4, ('Notificar al proveedor')
        WAITING_GOODS = 5, ('Esperando mercancias')
        COMPLETE = 6, ('Completado')
    name = models.CharField(
        max_length=254,
        help_text = "Nombre corto de la orden de compra"
    )
    description = models.TextField(
        max_length=1023,
        help_text="Descripción corta de la orden de compra",
        null=True,
        blank=True,
    )
    activity = models.ForeignKey(
        Activity,
        on_delete=models.CASCADE,
        related_name = 'orders',
        null = True,
        blank = True,
        help_text = "Actividad"
    )
    supplier =  models.ForeignKey(
        Supplier,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        help_text="Seleccione proveedor, si no existe dejar en blanco y agregar despues"
    )
    creation_date = models.DateTimeField(
        auto_now = True,
        editable = False,
    )
    end_date = models.DateTimeField(
        auto_now = False,
        editable = True,
        null = True,
        blank = True,
        help_text="Fecha limite para colocar orden"
    )
    status = models.IntegerField(
        choices = status.choices,
        default = 1,
    )
    delivery_conditions = models.TextField(
        max_length=255,
        help_text="Condiciones de entrega del proveedor",
        null=True,
        blank=True,
    )
    delivery_time = models.CharField(
        max_length=30,
        help_text="Tiempo de entrega promedio del proveedor",
        null=True,
        blank=True,
    )
    payment_conditions = models.CharField(
        max_length=255,
        help_text="Condiciones de pago por defecto del proveedor",
        blank=True,
        null = True,
    )
    request_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name = '%(class)s_request',
        null=True,
        blank=True,
        help_text="Quien solicita esta OC"
    )
    approved_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name = '%(class)s_approved',
        null=True,
        blank=True,
        help_text="Quien aprueba esta OC"
    )
    authorized_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name = '%(class)s_authorized',
        null=True,
        blank=True,
        help_text="Quien autoriza esta OC"
    )
    paid_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name = '%(class)s_paid',
        null=True,
        blank=True,
        help_text="Quien paga esta OC"
    )
    total = models.DecimalField(
        max_digits=10,
        decimal_places=3,
        blank=True,
        null=True,
        help_text = "Monto total e la OC"
    )

    def __str__(self):
        return str(self.pk)

app/finances/templates/finances/attendance_report.html
{% extends '__base.html' %}
{% load finance_extra %}

{% block title %}
    Lista de asistencia
{% endblock title %}

{% block finances_menu %}
<ul>
    <li><a href="{% url 'finances:finances_home' %}">Movimientos</a></li>
    <li><a href="{% url 'finances:order_list' %}">OC's</a></li>
    {% if perms.finances.change_movement %}
    <li><a href="{% url 'finances:finances_resume' %}">Resumen</a></li>
    <li><a href="{% url 'finances:attendance_form' %}">Asistencia</a></li>
    <li><a href="{% url 'finances:workerstime_list' %}">Horas-proyecto</a></li> 
    {% endif %}
</ul>
{% endblock %}

{% block content %}

<h2>
desde {{ inicio }} hasta {{ final }}
</h2>


<table class="project-table">
    <thead>
        <tr>
            <th scope="col">
                Nombre
            </th>
            {% for each_day in days %}
            <th scope="col" class="colincl">
                <a href="{% url 'projects:report_dayarchive' each_day|date:'Y' each_day|date:'b' each_day|date:'d' %}">
                    {{ each_day|date:'Y-b-d' }}
                </a>
            </th>
            {% endfor %}
        </tr>
    </thead>
    {% for user in calendar %}
    <tr>
        <th scope="row">{{user.user.last_name}} {{user.user.first_name}}</th>
        {% for day in user.hours %}
        <td scope="row">
        {% if day > 0 %}
            {{day|floatformat}}
        {% else %}
             - - 
        {% endif %}
        </td>
        {% endfor %}
    </tr>
    {% endfor %}
</table>

<a class="button" href="{% url 'profiles:workerattendance_week' inicio final extra adicional cliente%}">
    Reportes faltantes
</a>

{% endblock content %}

app/finances/templates/finances/movement_form.html
{% extends '__base.html' %}
{% load finance_extra %}

{% block title %}
    Movimientos
{% endblock title %}

{% block finances_menu %}
<ul>
    <li><a href="{% url 'finances:finances_home' %}">Movimientos</a></li>
    <li><a href="{% url 'finances:order_list' %}">OC's</a></li>
    {% if perms.finances.change_movement %}
    <li><a href="{% url 'finances:finances_resume' %}">Resumen</a></li>
    <li><a href="{% url 'finances:attendance_form' %}">Asistencia</a></li>
    <li><a href="{% url 'finances:workerstime_list' %}">Horas-proyecto</a></li> 
    {% endif %}
</ul>
{% endblock %}

{% block content %}
<div class="col col-lg-3">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_table}}
        <input class="btn btn-primary mb-3" type="submit" value="Enviar">
    </form>
</div>

<div class="col col-lg-9">
    <h2>Balance del mes actual</h2>
    <p>
        Total facturable: ${{total_fact|floatformat:"2g"}}
    </p>
    <p>
        Total no facturable: ${{total_no_fact|floatformat:"2g"}}
    </p>

    <h2>Movimientos facturables</h2>
    <table class="project-table">
        <thead>
            <tr>
                <th scope="col">Proveedor</th>
                <th scope="col">Día</th>
                <th scope="col">Descripción</th>
                <th scope="col">Monto</th>
                <th scope="col">Pagado</th>
                <th scope="col">Archivo</th>
                <th scope="col">Acción</th>
            </tr>
        </thead>
        {% for reg in invoice %}
        <tr {% if reg.amount < 0 %}
        class="negative"
        {% endif %}>
            <td scope="col">{{ reg.payee }}</td>
            <td scope="col">{{ reg.creation_date|date:"d" }}</td>
            {% if reg.description|wordcount > 10 %}
            <td scope="col" title="{{ reg.description }}">
                    {{ reg.description|truncatewords:'10' }}
            </td>
            {% else %}
            <td scope="col">{{ reg.description }}</td>
            {% endif %}
            <td scope="col">{{ reg.amount|floatformat:"2g" }}</td>
            <td scope="col">
                {% if reg.payment %}
                    &#9745; 
                {% else %}
                    &#9744;
                {% endif %}
            <td scope="col">
                {% if reg.files %}
                <a href="{{ reg.files.url }}">{{reg.files|filename}}</a>
                {% endif %}
            </td>
            <th scope="col"><a class="btn btn-outline-danger" href="{% url 'finances:finances_delete' reg.pk %}" role="button">&#9249;</a></th>
        </tr>
        {% endfor %}
    </table>

    <h2>Movimientos NO facturables</h2>

    <table class="project-table">
        <thead>
            <tr>
                <th scope="col">Proveedor</th>
                <th scope="col">Día</th>
                <th scope="col">Description</th>
                <th scope="col">Monto</th>
                <th scope="col">Pago</th>
                <th scope="col">Acción</th>
            </tr>
        </thead>
        {% for reg in no_invoice %}
        <tr {% if reg.amount < 0 %}
        class="negative"
        {% endif %}>
            <td scope="col">{{ reg.payee }}</td>
            <td scope="col">{{ reg.creation_date|date:"d" }}</td>
            {% if reg.description|wordcount > 10 %}
            <td scope="col" title="{{ reg.description }}">
                    {{ reg.description|truncatewords:'10' }}
            </td>
            {% else %}
            <td scope="col">{{ reg.description }}</td>
            {% endif %}
            <td scope="col">${{ reg.amount|floatformat:"2g" }}</td>
            <td scope="col">
                {% if reg.payment %}
                    &#9745;    
                {% else %}
                    &#9744;
                {% endif %}
            <th scope="col"><a class="btn btn-outline-danger" href="{% url 'finances:finances_delete' reg.pk %}" role="button">&#9249;</a></th>
        </tr>
        {% endfor %}
    </table>
</div>

<a class="button" href="{% url 'finances:finances_lastmonth' %}?responsable={{request.user.pk}}">
    Historico
</a>

{% endblock content %}

{% block scripts %}
{% endblock %}

app/finances/templates/finances/order_list.html
{% extends '__base.html' %}

{% block title %}
    Lista de ordenes de compra
{% endblock title %}

{% block finances_menu %}
<ul>
    <li><a href="{% url 'finances:finances_home' %}">Movimientos</a></li>
    <li><a href="{% url 'finances:order_list' %}">OC's</a></li>
    {% if perms.finances.change_movement %}
    <li><a href="{% url 'finances:finances_resume' %}">Resumen</a></li>
    <li><a href="{% url 'finances:attendance_form' %}">Asistencia</a></li>
    <li><a href="{% url 'finances:workerstime_list' %}">Horas-proyecto</a></li> 
    {% endif %}
</ul>
{% endblock %}

{% block content %}
{% load static %}

{% url 'finances:order_create' as url_all %}
{% url 'finances:order_create' as url_my %}

<a class='button' href="{% url 'finances:order_create' %}">Nueva OC</a>
{% if request.GET.terminadas %}
<a class='button' href="?">Mostrar en proceso</a>
{% else %}
<a class='button' href="?terminadas=True">Mostrar terminadas</a>
{% endif %}

<table class="project-table">
    <thead class="table">
        <tr>
            <th scope="col">NOMBRE</th>
            <th scope="col">FECHA</th>
            <th scope="col">PROYECTO</th>
            <th scope="col">PROVEEDOR</th>
            <th scope="col">ESTADO</th>
            <th scope="col">TOTAL</th>
        </tr>
    </thead>
    {% for order in orders %}
    <tr>
        <th scope="col">
            <a href="{% url 'finances:order_detail' order.pk %}">
                <img src = "{% static 'icons/icons-link.png' %}" alt="detail-icon" width="15" /></a>
            <a href="{% url 'finances:order_update' order.pk %}">
                <img src = "{% static 'icons/icons-edit.svg' %}" alt="edit-icon"/></a>
             {{ order.name }}
        </th>
        <td scope="col">{{ order.creation_date|date:'Y-m-d' }}</td>
        <td scope="col">
            {% if order.activity.project.cc_number %}
            CC-INX-{{ order.activity.project.cc_number }}
            {% else %}
            ¡SIN PROYECTO!
            {% endif  %}</td>
        <td scope="col">{{ order.supplier|title }}</td>
        <td scope="col">
            {{ order.get_status_display|title }}
            {% if order.status < 6 %}
            <a href="{% url 'finances:order_complete' order.pk %}">
                <spam> &#x26c4; </spam></a>
                {% comment %} <img src = "{% static 'icons/icons-edit.svg' %}" alt="edit-icon"/></a> {% endcomment %}
            {% endif %}
        </td>
        <td scope="col" class="proj-table-total">
            ${{ order.total|floatformat:'2g' }}
        </td>
    </tr>
    {% endfor %}
</table>

<div class="pagination">
    {% if page_obj.has_previous %}
    {% if request.GET.status %}
    <a class='button' href="?status={{request.GET.status}}&page=1">&laquo; primera</a>
    <a class='button' href="?status={{request.GET.status}}&page={{ page_obj.previous_page_number }}">anterior</a>
    {% else %}
    <a class='button' href="?page=1">&laquo; primera</a>
    <a class='button' href="?page={{ page_obj.previous_page_number }}">anterior</a>
    {% endif %}
    {% endif %}
    
    <span>pagina {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</span>
    
    {% if page_obj.has_next %}
    {% if request.GET.status %}
    <a class='button' href="?status={{request.GET.status}}&page={{ page_obj.next_page_number }}">siguiente</a>
    <a class='button' href="?status={{request.GET.status}}&page={{ page_obj.paginator.num_pages }}">ultima &raquo;</a>
    {% else %}
        <a class='button' href="?page={{ page_obj.next_page_number }}">siguiente</a>
        <a class='button' href="?page={{ page_obj.paginator.num_pages }}">ultima &raquo;</a>
    {% endif %}
    {% endif %}
</div>



{% endblock content %}

app/finances/templates/finances/useraccounting.html
{% extends '__base.html' %}
{% load finance_extra %}

{% block title %}
Resumen de viaticos
{% endblock title %}

{% block finances_menu %}
<ul>
    <li><a href="{% url 'finances:finances_home' %}">Movimientos</a></li>
    <li><a href="{% url 'finances:order_list' %}">OC's</a></li>
    {% if perms.finances.change_movement %}
    <li><a href="{% url 'finances:finances_resume' %}">Resumen</a></li>
    <li><a href="{% url 'finances:attendance_form' %}">Asistencia</a></li>
    <li><a href="{% url 'finances:workerstime_list' %}">Horas-proyecto</a></li> 
    {% endif %}
</ul>
{% endblock %}

{% block content %}
{% load static %}
<div class="col col-lg-9">
    <h2>
        Resumen de viaticos
    </h2>
    <p>
        {% for each in resumen %}
        <p> 
            <a href="{% url 'finances:finances_lastmonth' %}?responsable={{each.pk}}">
                <img src = "{% static 'icons/icons-link.png' %}" alt="detail-icon" width="15" /></a>
            {{each.last_name}}, {{each.first_name}}: $ {{each.total|stringformat:"2.2f"}}
        </p>
        {% endfor %}
    </p>
{% endblock %}