app/inxcontrol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('inxcontrol/admin/', admin.site.urls),
    path('inxcontrol/profiles/', include('profiles.urls'), name='profiles'),
    path('inxcontrol/finances/', include('finances.urls'), name='finances'),
    path('inxcontrol/projects/', include('projects.urls'), name='projects'),
    path('inxcontrol/sales/', include('sales.urls'), name='sales'),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

app/projects/urls.py
from django.urls import path

from .views import ( ProjectCreateView, ProjectListView, ProjectDetailView,
                     ProjectUpdateView, ActivityCreateView, ActivityDetailView,
                     ActivityListView, RequirementCreateView, RequirementListView,
                     ReportCreateView, ReportListView, ReportUpdateView, ActivityUpdateView,
                     ReportDetailView, PhotoCreateView, RequirementUpdateView,
                     ActivityDeleteView, ActivityCompactListView, ReportCardListView,
                     ActivityProgressCreateView, ReportProgressCreateView,
                     ActivityProgressUpdateView, ReportProgressUpdateView,
                     ReportProgressDeleteView, ActivityProgressDeleteView, SearchListView,
                     ReportDeleteView, ReportDayArchiveView, ReportLastdayArchiveView,
                     ActivityPrintView, RequirementCompleteView, ProjectCostUpdateView,
                     ProjectDeleteView, ReportMaterialsCreateView, ReportMaterialsDeleteView,
                     ReportListPrint, ActivityReportView, UserTimeReportUpdateView,
                     UserTimeReportConvertView, UserTimeReportAddView, ActivityWorkingListView,
                     UserReportListView )
app_name = 'projects'

urlpatterns = [
    path('projectlist', ProjectListView.as_view(), name='project_list' ),
    path('projectcreate', ProjectCreateView.as_view(),name='project_create'),
    path('projectdelete/<int:pk>', ProjectDeleteView.as_view(),name='project_delete'),
    path("projectdetail/<int:pk>", ProjectDetailView.as_view(), name = 'project_detail'),
    path('projectupdate/<int:pk>', ProjectUpdateView.as_view(), name='project_update' ),
    path('projectcostupdate/<int:pk>', ProjectCostUpdateView.as_view(), name='projectcost_update' ),
    path('activitylist', ActivityListView.as_view(), name='activity_list'),
    path('activityprint', ActivityPrintView.as_view(), name='activity_print'),
    path('activitycompactlist', ActivityCompactListView.as_view(), name='activity_compactlist'),
    path('activitycreate', ActivityCreateView.as_view(), name='activity_create'),
    path('activitydetail/<int:pk>', ActivityDetailView.as_view(), name='activity_detail'),
    path('activityupdate/<int:pk>', ActivityUpdateView.as_view(), name='activity_update'),
    path('activitydelete/<int:pk>', ActivityDeleteView.as_view(), name='activity_delete'),
    path('activityworkinglist', ActivityWorkingListView.as_view(), name='activity_workinglist'),
    path('activityreport', ActivityReportView.as_view(), name='activity_report'),
    path('activityprogresscreate/<int:pk>', ActivityProgressCreateView.as_view(), name='activityprogress_create'),
    path('activityprogressupdate/<int:pk>', ActivityProgressUpdateView.as_view(), name='activityprogress_update'),
    path('activityprogressdelete/<int:pk>', ActivityProgressDeleteView.as_view(), name='activityprogress_delete'),
    path('requirementcreate', RequirementCreateView.as_view(), name='requirement_create'),
    path('requirementupdate/<int:pk>', RequirementUpdateView.as_view(), name='requirement_update'),
    path('requirementlist', RequirementListView.as_view(), name='requirement_list'),
    path('requirementcomplete/<int:pk>', RequirementCompleteView.as_view(), name='requirement_complete'),
    path('reportlist', ReportListView.as_view(), name='report_list'),
    path('reports/lastday', ReportLastdayArchiveView.as_view(), name='report_lastday'),
    path('reports/<int:year>/<str:month>/<int:day>/', ReportDayArchiveView.as_view(), name='report_dayarchive'),
    path('reportcardlist', ReportCardListView.as_view(), name='report_cardlist'),
    path('reportcreate', ReportCreateView.as_view(), name='report_create'),
    path('reportcreate/<int:pk>', ReportProgressCreateView.as_view(), name='report2_create'),
    path('reportdelete/<int:pk>', ReportDeleteView.as_view(), name='report_delete'),
    path('userreportlist/<int:pk>', UserReportListView.as_view(), name='userreport_list'),
    path('reportprogressupdate/<int:pk>', ReportProgressUpdateView.as_view(), name='reportprogress_update'),
    path('reportprogresdelete/<int:pk>', ReportProgressDeleteView.as_view(), name='reportprogress_delete'),
    path('reportupdate/<int:pk>', ReportUpdateView.as_view(), name='report_update'),
    path('reportdetail/<int:pk>', PhotoCreateView.as_view(), name='report_detail'),
    path('reportlistprint', ReportListPrint.as_view(), name='report_listprint'),
    path('reportmaterialscreate/<int:pk>', ReportMaterialsCreateView.as_view(), name='reportmaterial_create'),
    path('reportmaterialsdelete/<int:pk>', ReportMaterialsDeleteView.as_view(), name='reportmaterial_delete'),
    path('usertimereportupdate/<int:pk>', UserTimeReportUpdateView.as_view(), name='usertimereport_update'),
    path('usertimereportconvert/<int:pk>', UserTimeReportConvertView.as_view(), name='usertimereport_convert'),
    path('usertimereportadd/<int:pk>', UserTimeReportAddView.as_view(), name='usertimereport_add'),
    path('search', SearchListView.as_view(), name='all_search'),
]

app/sales/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView

from .views import (ReportCreateView, ReportListView, ReportDetailView,
                    ReportDeleteView, OpportunityCreateView, OpportunityListView,
                    OpportunityDetailView, OpportunityDeleteView, update_status,
                    OpportunityTableView, OpportunityUpdateView
                    )

app_name = 'sales'

urlpatterns = [
    path('', ReportListView.as_view(), name='report_list'),
    path('reportcreate', ReportCreateView.as_view(), name='report_create'),
    path('report/<int:pk>', ReportDetailView.as_view(), name='report_detail'),
    path('report/<int:pk>/delete', ReportDeleteView.as_view(), name='report_delete'),
    path('opportunitycreate', OpportunityCreateView.as_view(), name='opportunity_create'),
    path('opportunitylist', OpportunityListView.as_view(), name='opportunity_list'),
    path('opportunitytable', OpportunityTableView.as_view(), name='opportunity_table'),
    path('opportunity/<int:pk>/update', OpportunityUpdateView.as_view(), name='opportunity_update'),
    path('opportunity/<int:pk>', OpportunityDetailView.as_view(), name='opportunity_detail'),
    path('opportunity/<int:pk>/delete', OpportunityDeleteView.as_view(), name='opportunity_delete'),
    path('update_status/<int:pk>/<int:new_status>', update_status, name='status_update')
]

app/projects/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save, m2m_changed

from profiles.models import Client, ClientContact
from django.contrib.auth.models import User
from django.core.files.uploadedfile import UploadedFile

from datetime import datetime
import os
from PIL import Image

def get_image_path(instance, filename):
    # print(instance.report.id)
    return os.path.join('reportes', str(instance.report.id), filename)

def get_thumbails_path(instance, filename):
    # print(instance.report.id)
    return os.path.join('thumbnails', filename)

class Project(models.Model):
    class Status(models.IntegerChoices):
        ACTIVO = 0, ("Activo")
        CIERRE_DOC = 1, ("Cierre Documental")
        PAUSADO = 2, ("Pausado")
        CERRADO = 3, ("Cerrado")
        CANCELADO = 4, ("Cancelado")
    
    class Types(models.IntegerChoices):
        PROY = 0, ("Proyecto")
        SUMI = 1, ("Suministro")
        SERV = 2, ("Servicio")
        FABR = 3, ("Fabricación")
        NOCO = 4, ("No contratado")

    cc_number = models.IntegerField(
        unique=True,
        null=True,
        blank=True,
        help_text="Numero de centro de costo"
    )
    name = models.CharField(
        max_length=255,
        help_text="Nombre del proyecto",
        null=True,
        blank=True,
    )
    type = models.IntegerField(
        choices=Types.choices,
        default=0,
        help_text="Tipo de proyecto",
        null=True,
    )
    date = models.DateField(
        auto_now=False,
        auto_now_add=False,
        default = datetime.now,
        null=True,
        blank=True,
        help_text='Fecha de inicio'
    )
    end_date = models.DateField(
        auto_now=False,
        auto_now_add=False,
        null = True,
        blank = True,
        help_text = "Fecha final del proyecto"
    )
    client = models.ForeignKey(
        Client,
        on_delete=models.SET_NULL,
        related_name='%(class)s_client',
        null = True,
        blank = True,
        help_text = "Nombre del cliente"
    )
    contact = models.ManyToManyField(
        ClientContact,
        blank = True,
    )
    manager = models.ForeignKey(
        User,
        null = True,
        blank = True,
        on_delete=models.SET_NULL,
        help_text = "Es quien dara seguimiento al proyecto"
    )
    status = models.IntegerField(
        choices=Status.choices,
        default=0,
        help_text="Estado actual del proyecto",
        null=True
    )
    labour_cost = models.DecimalField(
        max_digits=9,
        decimal_places=2,
        blank=True,
        null=True,
        help_text="Monto considerado para mano de obra del proyecto"
    )
    supply_cost = models.DecimalField(
        max_digits=9,
        decimal_places=2,
        blank=True,
        null=True,
        help_text="Monto considerado para suministros del proyecto"
    )

    def __str__(self):
        return 'INX-CC-{}: {}'.format(self.cc_number, self.name)

class Activity(models.Model):
    class Status(models.IntegerChoices):
        NEW = 0, ('Nueva')
        IN_PROCESS = 1, ('En proceso')
        FINISHED = 2, ('Terminada')
        UNFINISHED = 3, ('Incompleta')
        CANCELED  = 4, ('Cancelada')
        
    class Types(models.IntegerChoices):
        ADDITIONAL = 0, ('Adicional')
        PROJECT = 1, ('Proyecto')
        ENGINEERING = 2, ('Ingenieria')
        SERVICE = 3, ('Servicio')
        OTHER  = 4, ('Otro')

    name = models.CharField(
        max_length= 50,
        help_text="Nombre corto de la actividad"
    )
    date = models.DateField(
        auto_now=False,
        auto_now_add=False,
        default = datetime.now,
        null=True,
        blank=True,
        help_text='Fecha de inicio'
    )
    end_date = models.DateField(
        auto_now=False,
        auto_now_add=False,
        null = True,
        blank = True,
        help_text = "Fecha estimada final de la actividada"
    )
    description = models.TextField(
        max_length=500,
        help_text="Descripcion adicional de la actividad si es necesario",
        null=True,
        blank=True,
    )
    type = models.IntegerField(
        choices=Types.choices,
        default = 0,
        help_text="Tipo de actividad",
    )
    status = models.IntegerField(
        choices=Status.choices,
        default = 0,
        help_text="Estado de la actividad"
    )
    project = models.ForeignKey(
        Project,
        on_delete = models.SET_NULL,
        null = True,
        blank = True,
        help_text = "Projecto al que pertenece")
    incharge = models.ForeignKey(
        User,
        null = True,
        blank = True,
        on_delete=models.SET_NULL,
        help_text = "Es el responsable de la actividad")

    def __str__(self):
        if self.project:
            return '[' + str(self.project.cc_number) + '] ' + str(self.project.name) + ': ' + str(self.name)
        else:
            return 'Sin proyecto: ' + self.name
        
    @receiver(post_save, sender=Project)
    def create_default_activity(sender, instance, created, **kwargs):
        if created:
            if instance.status == 0:
                act = Activity()
                act.name = "No planeadas CC-INX-" + str(instance.cc_number)
                act.description = instance
                act.project = instance
                act.save()

class ActivityProgress(models.Model):
    name = models.CharField(
        max_length=96,
        null=True,
        blank = True,
        help_text='Nombre de la medida de progreso'
    )
    amount = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        blank=True,
        null=True,
        help_text='Cantidad requerida',
    )
    unit = models.CharField(
        max_length=32,
        null=True,
        blank=True,
        help_text='Unidad de medida',
    )
    activity = models.ForeignKey(
        Activity,
        on_delete=models.CASCADE,
        null=True,
        help_text='En que actividad se utiliza',
    )

class Requirements(models.Model):
    class status(models.IntegerChoices):
        PENDIENTE = 0, ('Pendiente')
        COMPLETO = 1, ('Completado')
        CANCEL = 2, ('Cancelado')

    name = models.CharField(
        max_length=50,
        help_text="Nombre corto del requerimiento"
    )
    request_date = models.DateField(
        auto_now=False,
        auto_now_add=False,
        default = datetime.now,
        null=True,
        blank=True,
        help_text='Fecha de solicitud'
    )
    supply_date = models.DateField(
        auto_now=False,
        auto_now_add=False,
        default = datetime.now,
        null=True,
        blank=True,
        help_text='Fecha de inicio'
    )
    by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name='%(class)s_by',
        blank=True,
        null=True,
        help_text="Trabajador que solicita el requerimiento"
    )
    to = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name='%(class)s_to',
        blank=True,
        null=True,
        help_text="Trabajador que debe entregar el requerimiento"
    )
    description=models.TextField(
        max_length=255,
        help_text="Descripcion de requerimiento",
    )
    amount=models.IntegerField(
        default=1,
        help_text="Cantidad de unidades del requerimiento"
    )
    unit = models.CharField(
        max_length=10,
        help_text="Unidad en las que se contabiliza el requerimiento"
    )
    activity = models.ForeignKey(
        Activity,
        on_delete=models.PROTECT,
        related_name='%(class)s_activities',
    )
    status = models.IntegerField(
        choices=status.choices,
        default = 0,
        help_text="Estado del requerimiento"
    )

    def __str__(self):
        return self.name

class Report(models.Model):
    class Deadtimetype(models.IntegerChoices):
        CLIENT = 0, ('A causa del cliente')
        MATERIAL = 1, ('Espera de materiales')
        WORKERS = 2, ('Espera de trabajadores')
        COMPLEX = 3, ('Tarea demaciado compleja')

    responsable = models.ForeignKey(
        User,
        related_name='%(class)s_responsable',
        on_delete=models.SET_NULL,
        null = True,
        blank = True,
        help_text = "Responsable de la actividad")
    date = models.DateField(
        default = datetime.now,
        help_text = "Fecha de la actividad AAAA-MM-DD"
    )
    name = models.CharField(
        max_length = 80,
        null=True,
        blank=True,
        help_text = "Nombre corto del reporte"
    )
    activity = models.ForeignKey(
        Activity,
        on_delete=models.SET_NULL,
        help_text="Seleccione la actividad",
        null=True,
        blank=True,
    )
    description = models.TextField(
        max_length=4096,
        help_text = "Descripción",
        null = True,
        blank = True)
    workers = models.ManyToManyField(
        User,
        related_name='%(class)s_workers',
        blank = True,
        help_text = "Ayudantes")
    duration = models.DecimalField(
        max_digits = 4,
        decimal_places = 2,
        null = True,
        blank = True,
        help_text = "Duración hora con punto decimal 1.5 = 1:30")
    deadtime = models.IntegerField(
        default=0,
        help_text="Tiempo muerto en minutos")
    deadtimereason = models.IntegerField(
        choices=Deadtimetype.choices,
        default=0,
        help_text="Razón por la cual se dio el tiempo muerto"
    )
    extratime = models.BooleanField(
        blank=True,
        null=True,
        help_text="Marcar si el reporte es en horas extras",
    )

    class meta:
        ordering = ['-date']

    def __str__(self):
        if self.name:
            return self.name
        else:
            return  self.date.strftime("%d/%m/%Y")

class UserTimeReport(models.Model):
    user = models.ForeignKey(
        User,

app/projects/templates/projects/activity_confirm_delete.html
{% extends '__base.html' %}

{% block title %}
    Borrar actividad
{% endblock title %}

{% block projects_menu %}
<ul>
    <li><a href="{% url 'projects:project_list' %}">Proyectos</a></li>
    <li><a href="{% url 'projects:activity_list' %}">Actividades</a></li>
    <li><a href="{% url 'projects:requirement_list' %}?status=0">Requerimientos</a></li>
    <li><a href="{% url 'projects:report_list' %}">Reportes</a></li>
</ul>
{% endblock%}

{% block content %}

<p>Seguro de borrar la actividad: ID:{{activity.pk}} nombre:{{activity.name}}</p>

<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Borar">
</form>

{% endblock content %}

app/projects/templates/projects/activityprogress_confirm_delete.html
{% extends '__base.html' %}

{% block title %}
    Borrar avance de actividad
{% endblock title %}

{% block projects_menu %}
<ul>
    <li><a href="{% url 'projects:project_list' %}">Proyectos</a></li>
    <li><a href="{% url 'projects:activity_list' %}">Actividades</a></li>
    <li><a href="{% url 'projects:requirement_list' %}?status=0">Requerimientos</a></li>
    <li><a href="{% url 'projects:report_list' %}">Reportes</a></li>
</ul>
{% endblock%}

{% block content %}

<p>Seguro de borrar el avance {{activityprogress.name}} de la actividad {{activityprogress.activity.name}}</p>

<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Borar">
</form>

{% endblock content %}

app/projects/templates/projects/photo_form.html
{% extends '__base.html' %}

{% block title %}
    Detalle de reporte
{% endblock title %}

{% block projects_menu %}
<ul>
    <li><a href="{% url 'projects:project_list' %}">Proyectos</a></li>
    <li><a href="{% url 'projects:activity_list' %}">Actividades</a></li>
    <li><a href="{% url 'projects:requirement_list' %}?status=0">Requerimientos</a></li>
    <li><a href="{% url 'projects:report_list' %}">Reportes</a></li>
</ul>
{% endblock%}

{% block content %}
{% load static %}
<div class="responsive-two-column-grid">
    <div>
        <ul>
            <li><b>ID / Fecha: </b>{{report.pk|stringformat:"04d"}} / {{report.date|date:'d-m-Y'}}</li>
            <li><b>Titulo: </b>{{report.name}}</li>
            <li>
                <b>Responsable: </b>
                {{report.responsable.last_name}} {{report.responsable.first_name}}
                <a href="{% url 'profiles:user_detail' report.responsable.pk %}">
                    <img src = "{% static 'icons/icons-link.png' %}" alt="edit-icon" width="15" />
                </a>
            </li>
            <li>
                <b>Proyecto: </b>
                {% if report.activity.project %}
                {{report.activity.project}}
                <a href="{% url 'projects:project_detail' report.activity.project.pk%}">
                    <img src = "{% static 'icons/icons-link.png' %}" alt="edit-icon" width="15" />
                </a>
                {% endif %}
            </li>
            <li>
                <b>Actividad: </b>
                {% if report.activity %}
                {{report.activity.name}}
                <a href="{% url 'projects:activity_detail' report.activity.pk %}">
                    <img src = "{% static 'icons/icons-link.png' %}" alt="edit-icon" width="15" />
                </a>
                {% endif %}
            </li>
            {% comment %} <li>
                {% for urt in report.usertimereport_set.all %}
                <b>Usuario: </b>
                {{urt.user.last_name}} {{urt.user.first_name}}
                {% endfor %}
            </li> {% endcomment %}
            {% if report.usertimereport_set.all %}
            <li><b>TRABAJADORES / Tiempo</b>
                <ul>
                    {% for urt in report.usertimereport_set.all %}
                    <li>
                        {{ urt.user.last_name }} {{ urt.user.first_name }} / {{ urt.duration }} hrs
                        <a href="{% url 'projects:usertimereport_update' urt.pk %}">
                            <img src = "{% static 'icons/icons-edit.svg' %}" alt="edit-icon"/>
                        </a>
                    </li>
                    {% endfor %}
                    <!-- Botón para agregar trabajadores a este reporte -->
                    <li>
                        <a class='button' href="{% url 'projects:usertimereport_add' report.pk %}">
                            Agregar trabajadores
                        </a>
                    </li>
                </ul>
            {% elif report.workers.all %}
            <li><b>TRABAJADORES:</b>
                <ul>
                    {% for worker in report.workers.all %}
                    <li>
                        {{ worker.last_name }} {{ worker.first_name }}
                        <a href="{% url 'profiles:user_detail' worker.pk %}">
                            <img src = "{% static 'icons/icons-link.png' %}" alt="edit-icon" width="15" />
                        </a> 
                    </li>
                    {% endfor %}
                    <!-- Botón para convertir trabajadores del reporte en tiempos individuales -->
                    <li>
                        <a class='button' href="{% url 'projects:usertimereport_convert' report.pk %}">
                            Convertir a tiempo individual
                        </a>
                    </li>
                </ul>
            </li>
            {% endif %}
            {% if report.activity.activityprogress_set.all %}
                <li><b>AVANCES:</b>
                {% if report.reportprogress_set.all %}
                    <ul>
                        {% for progress in report.reportprogress_set.all %}
                        <li>
                            {{ progress.amount }} {{ progress.activityprogress.unit }} de {{ progress.activityprogress.name }}
                            <a href="{% url 'projects:reportprogress_update' progress.id %}">
                                <img src = "{% static 'icons/icons-edit.svg' %}" alt="edit-icon"/>
                            </a>
                            <a href="{% url 'projects:reportprogress_delete' progress.id %}">
                                <img src = "{% static 'icons/icons-delete.svg' %}" alt="delete-icon"/>
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <a class='button' href="{% url 'projects:report2_create' report.pk %}">
                        Agregar avances
                    </a>
                {% endif %}
                </li>
            {% endif %}
            <li>
                <b>ACCIONES: </b>
                <a class='button' href="{% url 'projects:report_update' report.pk %}">EDITAR</a>
            </li>
        </ul>
        <h2>Materiales utilizados</h2>

        <table class="project-table">
            <thead>
                <tr>
                    <th width="60%">Descripción</th>
                    <th width="20%">Cantidad</th>
                    <th width="20%">Unidad</th>
                </tr>
            </thead>
            <tbody>
                {% for material in report.reportmaterials_set.all %}
                <tr>
                    <td>{{material.description}}</td>
                    <td>{{material.amount}}</td>
                    <td>{{material.unit}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a class="button" href="{% url 'projects:reportmaterial_create' report.pk %}">Agregar materiales</a>    
    </div>
    <div>
        <b>Descripción: </b>
        {{report.description|linebreaks}}
            <b>Duración: </b>{{report.duration}}
            <b>Tiempo muerto: </b>{{report.deadtime}} <b>min</b>  {{report.get_deadtimereason_display}}<br>
        {% comment %} <div class='thumbnail'>
            {% for photo in report.photo_set.all %}
                <div>
                    <a href="{{photo.pictures.url}}">
                        {% if photo.thumbnail %}
                            <img src="{{photo.thumbnail.url}}">
                        {% else %}
                            <img src = "{% static 'icons/icon-file.svg' %}" alt="file-icon"/>
                        {% endif %}
                    </a>
                </div>
            {% endfor %}
        </div> {% endcomment %}

        {% include 'projects/photo_gallery.html' %}
        
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Agregar fotos">
        </form>

    </div>
</div>
<br>

{% endblock content %}

app/projects/templates/projects/report_archive_day.html
{% extends '__base.html' %}

{% block title %}
    Lista de reportes
{% endblock title %}

{% block projects_menu %}
<ul>
    <li><a href="{% url 'projects:project_list' %}">Proyectos</a></li>
    <li><a href="{% url 'projects:activity_list' %}">Actividades</a></li>
    <li><a href="{% url 'projects:requirement_list' %}?status=0">Requerimientos</a></li>
    <li><a href="{% url 'projects:report_list' %}">Reportes</a></li>
</ul>
{% endblock%}

{% block content %}

<h4>Todos los reportes del dia {{ day }}</h4>

{% load static %}
{% for report in reports %}
<div class="responsive-two-column-grid">
    <div>
        <ul>
            <li><b>ID / Fecha: </b>{{report.pk|stringformat:"04d"}} / {{report.date|date:'d-m-Y'}}</li>
            <li><b>Titulo: </b>
                {{report.name}}
                <a href="{% url 'projects:report_update' report.pk %}">
                    <img src = "{% static 'icons/icons-edit.svg' %}" alt="edit-icon"/>
                </a>
                <a href="{% url 'projects:report_detail' report.pk %}">
                    <img src = "{% static 'icons/icons-link.png' %}" alt="detail-icon" width="15" />
                </a>
                </a>
                <a href="{% url 'projects:report_delete' report.pk %}">
                    <img src = "{% static 'icons/remove.png' %}" alt="remove-icon" width="15" />
                </a>
            </li>
            <li><b>Responsable: </b>{{report.responsable.last_name}} {{report.responsable.first_name}}</li>
            <li><b>Proyecto: </b>{{report.activity.project}}</li>
            <li><b>Actividad: </b>{{report.activity.name}}</li>
            <li><b>Avance: </b>
                {% for progress in report.reportprogress_set.all %}
                    {{ progress.amount|floatformat }} de {{ progress.activityprogress.amount|floatformat }} {{ progress.activityprogress.unit }}, 
                {% endfor %}
            </li>
            {% if report.usertimereport_set.all %}
            <li><b>TRABAJADORES / Tiempo</b>
                <ul>
                    {% for urt in report.usertimereport_set.all %}
                    <li>
                        {{ urt.user.last_name }} {{ urt.user.first_name }} / {{ urt.duration }} hrs
                        <a href="{% url 'projects:usertimereport_update' urt.pk %}">
                            <img src = "{% static 'icons/icons-edit.svg' %}" alt="edit-icon"/>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            {% elif report.workers.all %}
            <li><b>TRABAJADORES:</b>
                <ul>
                    {% for worker in report.workers.all %}
                    <li>
                        {{ worker.last_name }} {{ worker.first_name }}, 
                    </li>
                    {% endfor %}
                </ul>
            </li>
            {% endif %}
        </ul>
        
    </div>
    <div>
        <b>Descripción: </b>
        {{report.description|linebreaks}}
            <b>Duración: </b>{{report.duration}}
            <b>Tiempo muerto: </b>{{report.deadtime}} <b>min</b>  {{report.get_deadtimereason_display}}<br>
        <div class='thumbnail'>
            {% for photo in report.photo_set.all %}
                <div>
                    <a href="{{photo.pictures.url}}">
                        {% if photo.thumbnail %}
                            <img src="{{photo.thumbnail.url}}">
                        {% else %}
                            <img src = "{% static 'icons/icon-file.svg' %}" alt="file-icon"/>
                        {% endif %}
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endfor %}

{% if previous_day %}
<a class="button" href="{% url 'projects:report_dayarchive' previous_day|date:'Y' previous_day|date:'b' previous_day|date:'d' %}">
    Dia anterior: {{ previous_day|date:'Y-b-d' }}
</a>
{% endif %}
{% if next_day %}
<a class="button" href="{% url 'projects:report_dayarchive' next_day|date:'Y' next_day|date:'b' next_day|date:'d' %}">
    Dia siguiente: {{ next_day|date:'Y-b-d' }}
</a>
{% endif %}

{% endblock content %}